### ISSUE TITLE
(request) Cookies prompt block and close page

### ISSUE THREAD

**Issue by adeliktas** [thomasschwarz96/grav-plugin-simple-cookie#7]
Hello, i would like to request this:
prompt (possibly central like a message box) every time you visit the page and consentcookie isnt set to allow and if prompt gets declined force close the page

Example:
if(cookieconsent_status.exists && cookieconsent_status == 'deny')
    if(prompt() == denied)
        closepage()

I have tried on my own to work on this, but i wasn't able to understand the plugin properly.
(I also didnt code in javascript before)
https://github.com/thomasschwarz96/grav-plugin-simple-cookie/blob/master/assets/cookieconsent.min.js
The syntax of the plugin without a proper structure(newlines and tabs) made it hard to read and worse to modify(even though i tried to format it somehow readable adding newlines after each { } ;)

Thanks in advance

**Comment by qw3rtty** [comment]
Hello @adeliktas 
My plugin is a wrapper over the Open-Source **Cookie Consent** library of Osano.
So you have to use one of the callbacks from the library.
Here is the Link for the JavaScript API:
https://www.osano.com/cookieconsent/documentation/javascript-api/

The syntax is desired because the file is minified ;).
Here you can download the library and get the unminfied file:
https://www.osano.com/cookieconsent/download/

I will not implement this feature. I think it is too hard to kick out the user if he not accepts the cookies.
